CREATE TABLE T_MEDICO (
    ID_MEDICO        NUMBER NOT NULL PRIMARY KEY,
    NM_MEDICO        VARCHAR2(100) NOT NULL,
    NM_ESPECIALIDADE VARCHAR2(100) NOT NULL
);

CREATE SEQUENCE SQ_T_MEDICO START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE T_PACIENTE (
    ID_PACIENTE  NUMBER NOT NULL PRIMARY KEY,
    NM_PACIENTE  VARCHAR2(100) NOT NULL,
    NM_EMAIL     VARCHAR2(100) NOT NULL
);

CREATE SEQUENCE SQ_T_PACIENTE START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE T_CONSULTA (
    ID_CONSULTA    NUMBER NOT NULL PRIMARY KEY,
    ID_PACIENTE    NUMBER NOT NULL,
    ID_MEDICO      NUMBER NOT NULL,
    DT_HORA        DATE NOT NULL,
    TP_CONSULTA    VARCHAR2(100) NOT NULL,
    ST_CONFIRMACAO VARCHAR2(1) NOT NULL,
    CONSTRAINT CK_T_CONSULTA_STATUS CHECK (ST_CONFIRMACAO IN ('P', 'C', 'D')),
    CONSTRAINT FK_T_CONSULTA_PACIENTE FOREIGN KEY (ID_PACIENTE)
        REFERENCES T_PACIENTE (ID_PACIENTE),
    CONSTRAINT FK_T_CONSULTA_MEDICO FOREIGN KEY (ID_MEDICO)
        REFERENCES T_MEDICO (ID_MEDICO)
);

CREATE SEQUENCE SQ_T_CONSULTA START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE T_LEMBRETE (
    ID_LEMBRETE  NUMBER NOT NULL PRIMARY KEY,
    ID_CONSULTA  NUMBER NOT NULL,
    DT_CRIACAO   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_T_LEMBRETE_CONSULTA FOREIGN KEY (ID_CONSULTA)
        REFERENCES T_CONSULTA (ID_CONSULTA)
);

CREATE SEQUENCE SQ_T_LEMBRETE START WITH 1 INCREMENT BY 1 NOCACHE;